// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application'

import RendererController from "./renderer_controller"
application.register("renderer", RendererController)

import TagInputController from "./tag_input_controller"
application.register("tag-input", TagInputController)

import UploadController from "./upload_controller"
application.register("upload", UploadController)
