version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  groups:
    shrine:
      patterns:
        - "shrine*"
        - "tus-server"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  allow:
    - dependency-type: "all"
  ignore:
    - dependency-name: "@uppy/dashboard"
  groups:
    uppy:
      patterns:
        - "@uppy/*"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
