# Inspired by https://github.com/Energy-Sparks/energy-sparks/blob/master/.github/actions/setup/action.yml
name: Setup
description: Set up Manyfold build environment
runs:
  using: composite
  steps:
    - uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: libglfw3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version-file: ".node-version"
    - name: Install yarn packages
      run: yarn install
