nodeLinker: node-modules
dedupePluginMode: dependabot-only

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-dedupe.cjs
    spec: "https://github.com/blimmer/yarn-plugin-dedupe/releases/download/v1.0.0/plugin-dedupe.js"
