blank_issues_enabled: true
contact_links:
  - name: Support Discussions
    url: https://github.com/manyfold3d/manyfold/discussions/new?category=support
    about: Having trouble, but can't pin it down to a specific bug? Ask the community for help!
  - name: Matrix Chat
    url: https://matrix.to/#/#manyfold:one.ems.host
    about: Come and talk to us live with problems, ideas, questions, anything!
  - name: Social Media
    url: https://3dp.chat/@manyfold
    about: Talk to us on Mastodon!
