require "rails_helper"

RSpec.describe Print::DuetService do
  subject(:service) { described_class.new(print_host: print_host) }

  let(:print_host) do
    instance_double(
      PrintHost,
      endpoint: "http://duet.example.com",
      credentials: "reprap"
    )
  end

  let(:file) do
    bytes = ";generated by test\nG28\n"
    attachment = instance_double(ModelFileUploader::UploadedFile, download: bytes)

    instance_double(
      ModelFile,
      mime_type: Mime[:gcode],
      filename: "test.gcode",
      attachment: attachment
    )
  end

  describe "#ok?" do
    it "is true when a session can be opened",
      vcr: {cassette_name: "Print_DuetService/connect_and_upload"} do
      expect(service.ok?).to be(true)
    end
  end

  describe "#upload" do
    context "when start_print is left at its default" do
      it "uploads the file, starts the print with M32, and returns true",
        vcr: {cassette_name: "Print_DuetService/connect_and_upload"} do
        expect(service.upload(file: file)).to be(true)
      end
    end

    context "when start_print is false" do
      it "uploads the file and returns true without issuing a code",
        vcr: {cassette_name: "Print_DuetService/upload_only"} do
        expect(service.upload(file: file, start_print: false)).to be(true)
      end
    end

    context "with an unsupported file type" do
      let(:bad_file) do
        instance_double(
          ModelFile,
          mime_type: Mime[:png],
          filename: "x.png",
          attachment: instance_double(ModelFileUploader::UploadedFile)
        )
      end

      it "raises before opening a session" do
        expect { service.upload(file: bad_file) }.to raise_error(ArgumentError)
      end
    end

    context "when the print is started" do
      let(:connection) { instance_double(Faraday::Connection) }
      let(:codes) { [] }

      before do
        session = instance_double(
          Faraday::Response,
          success?: true,
          body: {"sessionKey" => "test-session-key"}.to_json
        )
        ok = instance_double(Faraday::Response, success?: true)
        request = Struct.new(:body)

        allow(Faraday).to receive(:new).and_return(connection)
        allow(connection).to receive(:put).and_return(ok)
        allow(connection).to receive(:get) do |url, *_rest, &block|
          if block
            req = request.new
            block.call(req)
            codes << req.body
          end
          url.to_s.include?("/machine/connect") ? session : ok
        end
      end

      it "sends M32 with the uploaded file's full path" do
        service.upload(file: file, start_print: true)

        expect(codes).to contain_exactly('M32 "0:/gcodes/test.gcode"')
      end

      it "sends no code at all when start_print is false" do
        service.upload(file: file, start_print: false)

        expect(codes).to be_empty
      end
    end
  end
end
