require "rails_helper"

RSpec.describe Print::PrusaLinkService do
  subject(:service) { described_class.new(print_host: print_host) }

  let(:print_host) do
    instance_double(
      PrintHost,
      endpoint: "http://prusalink.example.com",
      credentials: "test-api-key"
    )
  end

  let(:file) do
    bytes = ";generated by test\nG28\n"
    attachment = instance_double(
      ModelFileUploader::UploadedFile,
      download: bytes,
      open: StringIO.new(bytes)
    )

    instance_double(
      ModelFile,
      mime_type: Mime[:gcode],
      filename: "test.gcode",
      attachment: attachment
    )
  end

  describe "#ok?" do
    it "is true when /api/version answers",
      vcr: {cassette_name: "Print_PrusaLinkService/v1_upload"} do
      expect(service.ok?).to be(true)
    end
  end

  describe "#upload" do
    context "when the printer advertises upload-by-put (v1 firmware)" do
      it "uploads via PUT to the v1 endpoint and returns true",
        vcr: {cassette_name: "Print_PrusaLinkService/v1_upload"} do
        expect(service.upload(file: file)).to be(true)
      end
    end

    context "when the printer does not advertise the capability (legacy firmware)" do
      it "falls back to the legacy multipart POST and returns true",
        vcr: {cassette_name: "Print_PrusaLinkService/legacy_upload"} do
        expect(service.upload(file: file)).to be(true)
      end
    end

    context "with an unsupported file type" do
      let(:bad_file) do
        instance_double(
          ModelFile,
          mime_type: Mime[:png],
          filename: "x.png",
          attachment: instance_double(ModelFileUploader::UploadedFile)
        )
      end

      it "raises before making any request" do
        expect { service.upload(file: bad_file) }.to raise_error(ArgumentError)
      end
    end

    context "with the start_print flag" do
      let(:connection) { instance_double(Faraday::Connection) }
      let(:version_response) do
        instance_double(
          Faraday::Response,
          success?: true,
          body: {"api" => "2.0.0", "capabilities" => capabilities}.compact.to_json
        )
      end

      before do
        allow(Faraday).to receive(:new).and_return(connection)
        allow(connection).to receive_messages(
          get: version_response,
          put: instance_double(Faraday::Response, success?: true),
          post: instance_double(Faraday::Response, success?: true)
        )
      end

      context "when the printer runs v1 firmware" do
        let(:capabilities) { {"upload-by-put" => true} }

        it "sends the RFC 8941 true value when starting the print" do
          service.upload(file: file, start_print: true)

          expect(connection).to have_received(:put).with(
            anything, anything, hash_including("Print-After-Upload" => "?1")
          )
        end

        it "sends the RFC 8941 false value when not starting the print" do
          service.upload(file: file, start_print: false)

          expect(connection).to have_received(:put).with(
            anything, anything, hash_including("Print-After-Upload" => "?0")
          )
        end
      end

      context "when the printer runs legacy firmware" do
        let(:capabilities) { nil }

        it "selects the file when starting the print" do
          service.upload(file: file, start_print: true)

          expect(connection).to have_received(:post).with(
            anything, hash_including(select: "true"), anything
          )
        end

        it "does not select the file when not starting the print" do
          service.upload(file: file, start_print: false)

          expect(connection).to have_received(:post).with(
            anything, hash_including(select: "false"), anything
          )
        end
      end
    end
  end
end
